# Generated by Django 4.2.6 on 2023-11-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
