# Generated by Django 4.2.6 on 2023-11-01 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cigar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating_avg', models.FloatField(null=True)),
                ('time_avg', models.IntegerField(null=True)),
                ('origin', models.CharField(max_length=50, null=True)),
                ('wrapper', models.CharField(max_length=50, null=True)),
                ('filler', models.CharField(max_length=50, null=True)),
                ('binder', models.CharField(max_length=50, null=True)),
                ('strength', models.CharField(max_length=50, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('length', models.FloatField(null=True)),
                ('gauge', models.IntegerField(null=True)),
                ('shape', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('image', models.URLField(null=True)),
                ('thumbnail', models.URLField(null=True)),
            ],
        ),
    ]
