# Generated by Django 4.2.6 on 2023-11-06 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cigar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cigar',
            name='wrapper_color',
        ),
        migrations.AddField(
            model_name='cigar',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cigar',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='cigar',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='cigar',
            name='binder',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cigar',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cigar.brand'),
        ),
        migrations.AlterField(
            model_name='cigar',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cigar',
            name='filler',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cigar',
            name='gauge',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cigar',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cigar',
            name='origin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cigar',
            name='rating_avg',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cigar',
            name='shape',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cigar',
            name='strength',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cigar',
            name='time_avg',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cigar',
            name='wrapper',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
