# Generated by Django 4.2.6 on 2023-11-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigar', '0002_remove_cigar_wrapper_color_cigar_color_cigar_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cigar',
            name='length',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cigar',
            name='rating_avg',
            field=models.FloatField(null=True),
        ),
    ]
