# Generated by Django 4.2.6 on 2023-11-13 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cigar', '0002_brand_cigar_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cigar',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cigar.brand'),
            preserve_default=False,
        ),
    ]
