# Generated by Django 4.2.6 on 2023-11-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigar', '0003_alter_cigar_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cigar',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
