# Generated by Django 4.2.6 on 2023-11-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigar', '0006_alter_cigar_image_alter_cigar_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cigar',
            name='image',
            field=models.URLField(default='https://media.istockphoto.com/id/173545983/photo/cigar-with-blank-label.jpg?s=170667a&w=0&k=20&c=ELrSKomP9GR5EsRaDAKgw-j4bwZ1edtz1if1YG5q-JM=', null=True),
        ),
    ]
